
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class AIControlledStorage : IStorage<NamelessRogue.Engine.Components.AI.NonPlayerCharacter.AIControlled>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.AI.NonPlayerCharacter.AIControlled component)
        {

            this.Id = component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.AI.NonPlayerCharacter.AIControlled component)
        {

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Components.AI.NonPlayerCharacter.AIControlled (AIControlledStorage thisType)
        {
            NamelessRogue.Engine.Components.AI.NonPlayerCharacter.AIControlled result = new NamelessRogue.Engine.Components.AI.NonPlayerCharacter.AIControlled();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator AIControlledStorage (NamelessRogue.Engine.Components.AI.NonPlayerCharacter.AIControlled  component)
        {
            AIControlledStorage result = new AIControlledStorage();
            result.FillFrom(result);
            return result;
        }

    }

}