
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class ArmorStatsStorage : IStorage<NamelessRogue.Engine.Components.ItemComponents.ArmorStats>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public Int32 DefenceValue { get; set; }

        [FlatBufferItem(3)]  public Int32 EvasionValue { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.ItemComponents.ArmorStats component)
        {

            this.DefenceValue = component.DefenceValue;

            this.EvasionValue = component.EvasionValue;

            this.Id = component.Id == null ? null : component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId == null ? null : component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.ItemComponents.ArmorStats component)
        {

            component.DefenceValue = this.DefenceValue;

            component.EvasionValue = this.EvasionValue;

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Components.ItemComponents.ArmorStats (ArmorStatsStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Components.ItemComponents.ArmorStats result = new NamelessRogue.Engine.Components.ItemComponents.ArmorStats();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator ArmorStatsStorage (NamelessRogue.Engine.Components.ItemComponents.ArmorStats  component)
        {
            if(component == null) { return null; }
            ArmorStatsStorage result = new ArmorStatsStorage();
            result.FillFrom(component);
            return result;
        }

    }

}