
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferEnum(typeof(byte))]
    public enum BiomesStorage : byte 
    {
         None,
         Forest,
         Swamp,
         Desert,
         Lake,
         River,
         Jungle,
         Tundra,
         SnowDesert,
         Mountain,
         Hills,
         Plains,
         Beach,
         Sea,
         Savannah,
    
    }
}
