
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class BuffStorage : IStorage<NamelessRogue.Engine.Components.Interaction.Buff>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public Int32 DurationInTurns { get; set; }

        [FlatBufferItem(3)]  public List<ModifierTypeStorage> Modifiers { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.Interaction.Buff component)
        {

            this.DurationInTurns = component.DurationInTurns;

            this.Modifiers = new List<ModifierTypeStorage>(component.Modifiers.Cast<ModifierTypeStorage>());

        }

        public void FillTo(NamelessRogue.Engine.Components.Interaction.Buff component)
        {

            component.DurationInTurns = this.DurationInTurns;

            component.Modifiers = new List<NamelessRogue.Engine.Components.Interaction.ModifierType>(this.Modifiers.Cast<NamelessRogue.Engine.Components.Interaction.ModifierType>());


        }

        public static implicit operator NamelessRogue.Engine.Components.Interaction.Buff (BuffStorage thisType)
        {
            NamelessRogue.Engine.Components.Interaction.Buff result = new NamelessRogue.Engine.Components.Interaction.Buff();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator BuffStorage (NamelessRogue.Engine.Components.Interaction.Buff  component)
        {
            BuffStorage result = new BuffStorage();
            result.FillFrom(result);
            return result;
        }

    }

}