
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class BuffsStorage : IStorage<NamelessRogue.Engine.Components.Interaction.Buffs>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public IList<BuffStorage> Children { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.Interaction.Buffs component)
        {
            
            this.Children = new List<BuffStorage>(component.Children.Select(x=>(BuffStorage)x));

            this.Id = component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.Interaction.Buffs component)
        {

            component.Children = new List<NamelessRogue.Engine.Components.Interaction.Buff>(this.Children.Select(x=>(NamelessRogue.Engine.Components.Interaction.Buff)x));

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Components.Interaction.Buffs (BuffsStorage thisType)
        {
            NamelessRogue.Engine.Components.Interaction.Buffs result = new NamelessRogue.Engine.Components.Interaction.Buffs();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator BuffsStorage (NamelessRogue.Engine.Components.Interaction.Buffs  component)
        {
            BuffsStorage result = new BuffsStorage();
            result.FillFrom(result);
            return result;
        }

    }

}