
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class BuildingStorage : IStorage<NamelessRogue.Engine.Components.Environment.Building>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Environment.Building component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Environment.Building component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Environment.Building (BuildingStorage thisType)
        {
            NamelessRogue.Engine.Components.Environment.Building result = new NamelessRogue.Engine.Components.Environment.Building();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator BuildingStorage (NamelessRogue.Engine.Components.Environment.Building  component)
        {
            BuildingStorage result = new BuildingStorage();
            result.FillFrom(result);
            return result;
        }

    }

}