
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class CharacterStorage : IStorage<NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character (CharacterStorage thisType)
        {
            NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character result = new NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator CharacterStorage (NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character  component)
        {
            CharacterStorage result = new CharacterStorage();
            result.FillFrom(result);
            return result;
        }

    }

}