
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class CommanderStorage : IStorage<NamelessRogue.Engine.Infrastructure.Commander>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Infrastructure.Commander component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Infrastructure.Commander component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Infrastructure.Commander (CommanderStorage thisType)
        {
            NamelessRogue.Engine.Infrastructure.Commander result = new NamelessRogue.Engine.Infrastructure.Commander();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator CommanderStorage (NamelessRogue.Engine.Infrastructure.Commander  component)
        {
            CommanderStorage result = new CommanderStorage();
            result.FillFrom(result);
            return result;
        }

    }

}