
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class CursorStorage : IStorage<NamelessRogue.Engine.Components.Interaction.Cursor>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Interaction.Cursor component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Interaction.Cursor component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Interaction.Cursor (CursorStorage thisType)
        {
            NamelessRogue.Engine.Components.Interaction.Cursor result = new NamelessRogue.Engine.Components.Interaction.Cursor();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator CursorStorage (NamelessRogue.Engine.Components.Interaction.Cursor  component)
        {
            CursorStorage result = new CursorStorage();
            result.FillFrom(result);
            return result;
        }

    }

}