
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class DamageStorage : IStorage<NamelessRogue.Engine.Components.Status.Damage>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public EntityStorage Source { get; set; }

        [FlatBufferItem(3)]  public Int32 DamageValue { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.Status.Damage component)
        {

            this.Source.FillFrom(component.Source);

            this.DamageValue = component.DamageValue;

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Status.Damage component)
        {

            this.Source.FillTo(component.Source);

            component.DamageValue = this.DamageValue;

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Status.Damage (DamageStorage thisType)
        {
            NamelessRogue.Engine.Components.Status.Damage result = new NamelessRogue.Engine.Components.Status.Damage();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator DamageStorage (NamelessRogue.Engine.Components.Status.Damage  component)
        {
            DamageStorage result = new DamageStorage();
            result.FillFrom(result);
            return result;
        }

    }

}