
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class DescriptionStorage : IStorage<NamelessRogue.Engine.Components.UI.Description>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public String Name { get; set; }

        [FlatBufferItem(3)]  public String Text { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.UI.Description component)
        {

            this.Name = component.Name;

            this.Text = component.Text;

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.UI.Description component)
        {

            component.Name = this.Name;

            component.Text = this.Text;

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.UI.Description (DescriptionStorage thisType)
        {
            NamelessRogue.Engine.Components.UI.Description result = new NamelessRogue.Engine.Components.UI.Description();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator DescriptionStorage (NamelessRogue.Engine.Components.UI.Description  component)
        {
            DescriptionStorage result = new DescriptionStorage();
            result.FillFrom(result);
            return result;
        }

    }

}