
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class DrawableStorage : IStorage<NamelessRogue.Engine.Components.Rendering.Drawable>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public ColorStorage BackgroundColor { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.Rendering.Drawable component)
        {

            this.BackgroundColor = component.BackgroundColor;

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Rendering.Drawable component)
        {

            component.BackgroundColor = this.BackgroundColor;

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Rendering.Drawable (DrawableStorage thisType)
        {
            NamelessRogue.Engine.Components.Rendering.Drawable result = new NamelessRogue.Engine.Components.Rendering.Drawable();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator DrawableStorage (NamelessRogue.Engine.Components.Rendering.Drawable  component)
        {
            DrawableStorage result = new DrawableStorage();
            result.FillFrom(result);
            return result;
        }

    }

}