
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class EquipmentSlotsStorage : IStorage<NamelessRogue.Engine.Components.ItemComponents.EquipmentSlots>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.ItemComponents.EquipmentSlots component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.ItemComponents.EquipmentSlots component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.ItemComponents.EquipmentSlots (EquipmentSlotsStorage thisType)
        {
            NamelessRogue.Engine.Components.ItemComponents.EquipmentSlots result = new NamelessRogue.Engine.Components.ItemComponents.EquipmentSlots();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator EquipmentSlotsStorage (NamelessRogue.Engine.Components.ItemComponents.EquipmentSlots  component)
        {
            EquipmentSlotsStorage result = new EquipmentSlotsStorage();
            result.FillFrom(result);
            return result;
        }

    }

}