
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class FireStorage : IStorage<NamelessRogue.Engine.Components.Environment.Fire>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Environment.Fire component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Environment.Fire component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Environment.Fire (FireStorage thisType)
        {
            NamelessRogue.Engine.Components.Environment.Fire result = new NamelessRogue.Engine.Components.Environment.Fire();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator FireStorage (NamelessRogue.Engine.Components.Environment.Fire  component)
        {
            FireStorage result = new FireStorage();
            result.FillFrom(result);
            return result;
        }

    }

}