
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class FurnitureStorage : IStorage<NamelessRogue.Engine.Components.Environment.Furniture>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Environment.Furniture component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Environment.Furniture component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Environment.Furniture (FurnitureStorage thisType)
        {
            NamelessRogue.Engine.Components.Environment.Furniture result = new NamelessRogue.Engine.Components.Environment.Furniture();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator FurnitureStorage (NamelessRogue.Engine.Components.Environment.Furniture  component)
        {
            FurnitureStorage result = new FurnitureStorage();
            result.FillFrom(result);
            return result;
        }

    }

}