
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class InputComponentStorage : IStorage<NamelessRogue.Engine.Components.Interaction.InputComponent>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Interaction.InputComponent component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Interaction.InputComponent component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Interaction.InputComponent (InputComponentStorage thisType)
        {
            NamelessRogue.Engine.Components.Interaction.InputComponent result = new NamelessRogue.Engine.Components.Interaction.InputComponent();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator InputComponentStorage (NamelessRogue.Engine.Components.Interaction.InputComponent  component)
        {
            InputComponentStorage result = new InputComponentStorage();
            result.FillFrom(result);
            return result;
        }

    }

}