
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class InputReceiverStorage : IStorage<NamelessRogue.Engine.Components.Interaction.InputReceiver>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Interaction.InputReceiver component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Interaction.InputReceiver component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Interaction.InputReceiver (InputReceiverStorage thisType)
        {
            NamelessRogue.Engine.Components.Interaction.InputReceiver result = new NamelessRogue.Engine.Components.Interaction.InputReceiver();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator InputReceiverStorage (NamelessRogue.Engine.Components.Interaction.InputReceiver  component)
        {
            InputReceiverStorage result = new InputReceiverStorage();
            result.FillFrom(result);
            return result;
        }

    }

}