
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class ItemsHolderStorage : IStorage<NamelessRogue.Engine.Components.ItemComponents.ItemsHolder>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public List<EntityStorage> Items { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.ItemComponents.ItemsHolder component)
        {

            this.Items = new List<EntityStorage>(component.Items.Cast<EntityStorage>());

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.ItemComponents.ItemsHolder component)
        {

            component.Items = new List<NamelessRogue.Engine.Abstraction.IEntity>(this.Items.Cast<NamelessRogue.Engine.Abstraction.IEntity>());

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.ItemComponents.ItemsHolder (ItemsHolderStorage thisType)
        {
            NamelessRogue.Engine.Components.ItemComponents.ItemsHolder result = new NamelessRogue.Engine.Components.ItemComponents.ItemsHolder();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator ItemsHolderStorage (NamelessRogue.Engine.Components.ItemComponents.ItemsHolder  component)
        {
            ItemsHolderStorage result = new ItemsHolderStorage();
            result.FillFrom(result);
            return result;
        }

    }

}