
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class LineToPlayerStorage : IStorage<NamelessRogue.Engine.Components.Rendering.LineToPlayer>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Rendering.LineToPlayer component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Rendering.LineToPlayer component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Rendering.LineToPlayer (LineToPlayerStorage thisType)
        {
            NamelessRogue.Engine.Components.Rendering.LineToPlayer result = new NamelessRogue.Engine.Components.Rendering.LineToPlayer();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator LineToPlayerStorage (NamelessRogue.Engine.Components.Rendering.LineToPlayer  component)
        {
            LineToPlayerStorage result = new LineToPlayerStorage();
            result.FillFrom(result);
            return result;
        }

    }

}