
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class MetaphysicalForceStorage : IStorage<NamelessRogue.Engine.Generation.World.MetaphysicalForce>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public String Name { get; set; }

        [FlatBufferItem(3)]  public ColorStorage Color { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.MetaphysicalForce component)
        {

            this.Name = component.Name;

            this.Color = component.Color;

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.MetaphysicalForce component)
        {

            component.Name = this.Name;

            component.Color = this.Color;


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.MetaphysicalForce (MetaphysicalForceStorage thisType)
        {
            NamelessRogue.Engine.Generation.World.MetaphysicalForce result = new NamelessRogue.Engine.Generation.World.MetaphysicalForce();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator MetaphysicalForceStorage (NamelessRogue.Engine.Generation.World.MetaphysicalForce  component)
        {
            MetaphysicalForceStorage result = new MetaphysicalForceStorage();
            result.FillFrom(result);
            return result;
        }

    }

}