
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class OccupiesTileStorage : IStorage<NamelessRogue.Engine.Components.Physical.OccupiesTile>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Physical.OccupiesTile component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Physical.OccupiesTile component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Physical.OccupiesTile (OccupiesTileStorage thisType)
        {
            NamelessRogue.Engine.Components.Physical.OccupiesTile result = new NamelessRogue.Engine.Components.Physical.OccupiesTile();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator OccupiesTileStorage (NamelessRogue.Engine.Components.Physical.OccupiesTile  component)
        {
            OccupiesTileStorage result = new OccupiesTileStorage();
            result.FillFrom(result);
            return result;
        }

    }

}