
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class PoliticalRelationStorage : IStorage<NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public IList<RelationsModifierStorage> Modifiers { get; set; }

        [FlatBufferItem(3)]  public RelationsStatusStorage Status { get; set; }

        [FlatBufferItem(4)]  public Int32 RelationshipPoints { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation component)
        {
            
            this.Modifiers = new List<RelationsModifierStorage>(component.Modifiers.Select(x=>(RelationsModifierStorage)x));

            this.Status = (RelationsStatusStorage)component.Status;

            this.RelationshipPoints = component.RelationshipPoints;

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation component)
        {

            component.Modifiers = new List<NamelessRogue.Engine.Generation.World.Diplomacy.RelationsModifier>(this.Modifiers.Select(x=>(NamelessRogue.Engine.Generation.World.Diplomacy.RelationsModifier)x));

            component.Status = (NamelessRogue.Engine.Generation.World.Diplomacy.RelationsStatus)this.Status;

            component.RelationshipPoints = this.RelationshipPoints;


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation (PoliticalRelationStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation result = new NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator PoliticalRelationStorage (NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation  component)
        {
            if(component == null) { return null; }
            PoliticalRelationStorage result = new PoliticalRelationStorage();
            result.FillFrom(component);
            return result;
        }

    }

}