
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class PoliticalRelationStorage : IStorage<NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public List<RelationsModifierStorage> Modifiers { get; set; }

        [FlatBufferItem(3)]  public RelationsStatusStorage Status { get; set; }

        [FlatBufferItem(4)]  public Int32 RelationshipPoints { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation component)
        {

            this.Modifiers = new List<RelationsModifierStorage>(component.Modifiers.Cast<RelationsModifierStorage>());

            this.Status = (RelationsStatusStorage)component.Status;

            this.RelationshipPoints = component.RelationshipPoints;

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation component)
        {

            component.Modifiers = new List<NamelessRogue.Engine.Generation.World.Diplomacy.RelationsModifier>(this.Modifiers.Cast<NamelessRogue.Engine.Generation.World.Diplomacy.RelationsModifier>());

            component.Status = (NamelessRogue.Engine.Generation.World.Diplomacy.RelationsStatus)this.Status;

            component.RelationshipPoints = this.RelationshipPoints;


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation (PoliticalRelationStorage thisType)
        {
            NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation result = new NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator PoliticalRelationStorage (NamelessRogue.Engine.Generation.World.Diplomacy.PoliticalRelation  component)
        {
            PoliticalRelationStorage result = new PoliticalRelationStorage();
            result.FillFrom(result);
            return result;
        }

    }

}