
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class PositionStorage : IStorage<NamelessRogue.Engine.Components.Physical.Position>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Physical.Position component)
        {

            this.Id = component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.Physical.Position component)
        {

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Components.Physical.Position (PositionStorage thisType)
        {
            NamelessRogue.Engine.Components.Physical.Position result = new NamelessRogue.Engine.Components.Physical.Position();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator PositionStorage (NamelessRogue.Engine.Components.Physical.Position  component)
        {
            PositionStorage result = new PositionStorage();
            result.FillFrom(result);
            return result;
        }

    }

}