
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class RegionStorage : IStorage<NamelessRogue.Engine.Generation.World.Region>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public ColorStorage Color { get; set; }

        [FlatBufferItem(3)]  public String Name { get; set; }

        [FlatBufferItem(4)]  public Int32 SizeInTiles { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.Region component)
        {

            this.Color = component.Color;

            this.Name = component.Name;

            this.SizeInTiles = component.SizeInTiles;

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.Region component)
        {

            component.Color = this.Color;

            component.Name = this.Name;

            component.SizeInTiles = this.SizeInTiles;


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.Region (RegionStorage thisType)
        {
            NamelessRogue.Engine.Generation.World.Region result = new NamelessRogue.Engine.Generation.World.Region();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator RegionStorage (NamelessRogue.Engine.Generation.World.Region  component)
        {
            RegionStorage result = new RegionStorage();
            result.FillFrom(result);
            return result;
        }

    }

}