
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class ScreenStorage : IStorage<NamelessRogue.Engine.Components.Rendering.Screen>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public Int32 Width { get; set; }

        [FlatBufferItem(3)]  public Int32 Height { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.Rendering.Screen component)
        {

            this.Width = component.Width;

            this.Height = component.Height;

            this.Id = component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.Rendering.Screen component)
        {

            component.Width = this.Width;

            component.Height = this.Height;

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Components.Rendering.Screen (ScreenStorage thisType)
        {
            NamelessRogue.Engine.Components.Rendering.Screen result = new NamelessRogue.Engine.Components.Rendering.Screen();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator ScreenStorage (NamelessRogue.Engine.Components.Rendering.Screen  component)
        {
            ScreenStorage result = new ScreenStorage();
            result.FillFrom(result);
            return result;
        }

    }

}