
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class SimpleStatStorage : IStorage<NamelessRogue.Engine.Components.Stats.SimpleStat>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public Int32 Value { get; set; }

        [FlatBufferItem(3)]  public Int32 MinValue { get; set; }

        [FlatBufferItem(4)]  public Int32 MaxValue { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.Stats.SimpleStat component)
        {

            this.Value = component.Value;

            this.MinValue = component.MinValue;

            this.MaxValue = component.MaxValue;

        }

        public void FillTo(NamelessRogue.Engine.Components.Stats.SimpleStat component)
        {

            component.Value = this.Value;

            component.MinValue = this.MinValue;

            component.MaxValue = this.MaxValue;


        }

        public static implicit operator NamelessRogue.Engine.Components.Stats.SimpleStat (SimpleStatStorage thisType)
        {
            NamelessRogue.Engine.Components.Stats.SimpleStat result = new NamelessRogue.Engine.Components.Stats.SimpleStat();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator SimpleStatStorage (NamelessRogue.Engine.Components.Stats.SimpleStat  component)
        {
            SimpleStatStorage result = new SimpleStatStorage();
            result.FillFrom(result);
            return result;
        }

    }

}