
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class SimpleSwitchStorage : IStorage<NamelessRogue.Engine.Components.Interaction.SimpleSwitch>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.Interaction.SimpleSwitch component)
        {

            this.Id = component.Id;

            this.ParentEntityId = component.ParentEntityId;

        }

        public void FillTo(NamelessRogue.Engine.Components.Interaction.SimpleSwitch component)
        {

            component.Id = this.Id;

            component.ParentEntityId = this.ParentEntityId;


        }

        public static implicit operator NamelessRogue.Engine.Components.Interaction.SimpleSwitch (SimpleSwitchStorage thisType)
        {
            NamelessRogue.Engine.Components.Interaction.SimpleSwitch result = new NamelessRogue.Engine.Components.Interaction.SimpleSwitch();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator SimpleSwitchStorage (NamelessRogue.Engine.Components.Interaction.SimpleSwitch  component)
        {
            SimpleSwitchStorage result = new SimpleSwitchStorage();
            result.FillFrom(result);
            return result;
        }

    }

}