
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferEnum(typeof(Int32))]
    public enum TerrainTypesStorage : Int32 
    {
         Nothingness,
         Dirt,
         Road,
         Water,
         Grass,
         Snow,
         Sand,
         Rocks,
         LightRocks,
         HardRocks,
    
    }
}
