
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class TileForInlandWaterConnectivityStorage : IStorage<NamelessRogue.Engine.Generation.World.TileForInlandWaterConnectivity>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public IList<WaterBorderLineStorage> WaterBorderLines { get; set; }

        [FlatBufferItem(3)] public int X { get; set; }

        [FlatBufferItem(4)] public int Y { get; set; }

        [FlatBufferItem(5)] public bool IsWater { get; set; }


        public void FillFrom(NamelessRogue.Engine.Generation.World.TileForInlandWaterConnectivity component)
        {
            
            this.WaterBorderLines = new List<WaterBorderLineStorage>(component.WaterBorderLines.Select(x=>(WaterBorderLineStorage)x));
            X = component.x;
            Y = component.y;
            IsWater = component.isWater;
        }

        public void FillTo(NamelessRogue.Engine.Generation.World.TileForInlandWaterConnectivity component)
        {

            component.WaterBorderLines = new List<NamelessRogue.Engine.Generation.World.WaterBorderLine>(this.WaterBorderLines.Select(x=>(NamelessRogue.Engine.Generation.World.WaterBorderLine)x));
            component.x = X;
            component.y = Y;
            component.isWater = IsWater;

        }

        public static implicit operator NamelessRogue.Engine.Generation.World.TileForInlandWaterConnectivity (TileForInlandWaterConnectivityStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Generation.World.TileForInlandWaterConnectivity result = new NamelessRogue.Engine.Generation.World.TileForInlandWaterConnectivity();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator TileForInlandWaterConnectivityStorage (NamelessRogue.Engine.Generation.World.TileForInlandWaterConnectivity  component)
        {
            if(component == null) { return null; }
            TileForInlandWaterConnectivityStorage result = new TileForInlandWaterConnectivityStorage();
            result.FillFrom(component);
            return result;
        }

    }

}