
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class WaterBorderLineStorage : IStorage<NamelessRogue.Engine.Generation.World.WaterBorderLine>
    {
            [FlatBufferItem(0)]  public Guid Id { get; set; }
            [FlatBufferItem(1)]  public Guid ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public List<PointStorage> Points { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.WaterBorderLine component)
        {

            this.Points = new List<PointStorage>(component.Points.Cast<PointStorage>());

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.WaterBorderLine component)
        {

            component.Points = new List<Microsoft.Xna.Framework.Point>(this.Points.Cast<Microsoft.Xna.Framework.Point>());


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.WaterBorderLine (WaterBorderLineStorage thisType)
        {
            NamelessRogue.Engine.Generation.World.WaterBorderLine result = new NamelessRogue.Engine.Generation.World.WaterBorderLine();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator WaterBorderLineStorage (NamelessRogue.Engine.Generation.World.WaterBorderLine  component)
        {
            WaterBorderLineStorage result = new WaterBorderLineStorage();
            result.FillFrom(result);
            return result;
        }

    }

}