
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class WorldBoardPlayerStorage : IStorage<NamelessRogue.Engine.Components.WorldBoardComponents.WorldBoardPlayer>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.WorldBoardComponents.WorldBoardPlayer component)
        {

            this.Id = component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.WorldBoardComponents.WorldBoardPlayer component)
        {

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Components.WorldBoardComponents.WorldBoardPlayer (WorldBoardPlayerStorage thisType)
        {
            NamelessRogue.Engine.Components.WorldBoardComponents.WorldBoardPlayer result = new NamelessRogue.Engine.Components.WorldBoardComponents.WorldBoardPlayer();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator WorldBoardPlayerStorage (NamelessRogue.Engine.Components.WorldBoardComponents.WorldBoardPlayer  component)
        {
            WorldBoardPlayerStorage result = new WorldBoardPlayerStorage();
            result.FillFrom(result);
            return result;
        }

    }

}