
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
using Microsoft.Xna.Framework;

namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class ColorStorage : IStorage<NamelessRogue.Engine.Utility.Color>, IStorage<Color>
    {
        [FlatBufferItem(0)] public string Id { get; set; }
        [FlatBufferItem(1)] public string ParentEntityId { get; set; }
        [FlatBufferItem(2)] public byte Red { get; set; }

        [FlatBufferItem(3)] public byte Green { get; set; }

        [FlatBufferItem(4)] public byte Blue { get; set; }

        [FlatBufferItem(5)] public byte Alpha { get; set; }

        public void FillFrom(NamelessRogue.Engine.Utility.Color component)
        {
            this.Red = (byte)(component.Red*255);

            this.Green = (byte)(component.Green*255);

            this.Blue = (byte)(component.Blue*255);

            this.Alpha = (byte)(component.Alpha);
        }

        public void FillFrom(Color component)
        {
            this.Red = component.R;

            this.Green = component.G;

            this.Blue = component.B;

            this.Alpha = component.A;
        }

        public void FillTo(NamelessRogue.Engine.Utility.Color component)
        {
            component.Red = this.Red/255f;

            component.Green = this.Green/255f;

            component.Blue = this.Blue/255f;

            component.Alpha = this.Alpha/255f;
        }

        public void FillTo(Color component)
        {
            component.R = this.Red;

            component.G = this.Green;

            component.B = this.Blue;

            component.A = this.Alpha;
        }

        public static implicit operator NamelessRogue.Engine.Utility.Color(ColorStorage thisType)
        {
            if (thisType == null) { return default; }
            NamelessRogue.Engine.Utility.Color result = new NamelessRogue.Engine.Utility.Color();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator ColorStorage(NamelessRogue.Engine.Utility.Color component)
        {
            if (component == null) { return null; }
            ColorStorage result = new ColorStorage();
            result.FillFrom(component);
            return result;
        }

        public static implicit operator Color(ColorStorage thisType)
        {
            if (thisType == null) { return default; }
            Color result = new Color();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator ColorStorage(Color component)
        {
            if (component == null) { return null; }
            ColorStorage result = new ColorStorage();
            result.FillFrom(component);
            return result;
        }


    }

}