using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Xml;
using System.Xml.Serialization;
using FlatSharp;
using FlatSharp.CodeGen;
using Microsoft.Xna.Framework;
using NamelessRogue.Engine.Abstraction;
using NamelessRogue.Engine.Components;
using NamelessRogue.Engine.Components.ChunksAndTiles;
using NamelessRogue.Engine.Components.Environment;
using NamelessRogue.Engine.Components.Interaction;
using NamelessRogue.Engine.Components.ItemComponents;
using NamelessRogue.Engine.Components.Rendering;
using NamelessRogue.Engine.Components.UI;
using NamelessRogue.Engine.Generation.Editor;
using NamelessRogue.Engine.Generation.World;
using NamelessRogue.Engine.Generation.World.BoardPieces;
using NamelessRogue.Engine.Infrastructure;
using NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.shell;
using Newtonsoft.Json;
using RogueSharp;
using Point = Microsoft.Xna.Framework.Point;

namespace NamelessRogue.Engine.Serialization
{

    public static class ObjectExtensions
    {
        public static T CastTo<T>(this object o) => (T)o;

        public static dynamic CastToReflected(this object o, Type type)
        {
            var methodInfo = typeof(ObjectExtensions).GetMethod(nameof(CastTo), BindingFlags.Static | BindingFlags.Public);
            var genericArguments = new[] { type };
            var genericMethodInfo = methodInfo?.MakeGenericMethod(genericArguments);
            return genericMethodInfo?.Invoke(null, new[] { o });
        }
    }

    public class SaveManager
    {
        static ByteSizesStorage ByteSizes { get; set; } = null;
        public static void Init()
        {
            if (!File.Exists("ByteSizesStorage.xml"))
            {
                ByteSizes = new ByteSizesStorage();
                XmlSerializer serializer = new XmlSerializer(typeof(ByteSizesStorage));
                using (var stream = File.OpenWrite("ByteSizesStorage.xml"))
                {
                    serializer.Serialize(stream, ByteSizes);
                }
            }
            {
                XmlSerializer serializer = new XmlSerializer(typeof(ByteSizesStorage));
                TextReader reader = new StreamReader("ByteSizesStorage.xml");
                ByteSizes = (ByteSizesStorage)serializer.Deserialize(reader);
                reader.Close();
            }
                FlatBufferSerializer.Default.Compile<NamelessRogueSaveFile>();
            //    FlatBufferSerializer.Default.Compile<TimelineStorage>();
        }
        public static void SaveGame(String pathToFolder, NamelessGame game)
        {
            return;
            var saveFile = new NamelessRogueSaveFile();
            Type iStorageInterfaceType = typeof(IStorage<>);

            foreach (var componentTypeCollection in EntityInfrastructureManager.Components)
            {
                if (componentTypeCollection.Key.GetCustomAttributes(true).Any(a => a.GetType() == typeof(NamelessRogue.Engine.Serialization.SkipClassGeneration)))
                {
                    continue;
                }

                foreach (var componentDictionary in componentTypeCollection.Value)
                {
                    //the type of the storage that can store current type
                    Type storageType = saveFile.ComponentTypeToStorge[componentTypeCollection.Key];

                    var constructor = storageType.GetConstructor(Type.EmptyTypes);
                    if (constructor == null)
                    {
                        throw new Exception($@"{storageType.Name} must contain a parameterless constructor in order for Save manager to serialize it");
                    }

                    dynamic storageObject = constructor.Invoke(null);

                    //storageObject.FillFrom(ObjectExtensions.CastToReflected(componentDictionary.Value, componentDictionary.Value.GetType()));

                    saveFile.StoragesDictionary[storageObject.GetType()].Add(storageObject);
                }
            }
            //foreach (var entity in EntityInfrastructureManager.Entities.Values)
            //{
            //    var storage = new EntityStorage();
            //    storage.FillFrom(entity);
            //    saveFile.EntityStorageTable.Add(storage);
            //}

            {
                int maxBytesNeeded = FlatBufferSerializer.Default.GetMaxSize(saveFile);
                byte[] buffer = new byte[maxBytesNeeded];
                int bytesWritten = FlatBufferSerializer.Default.Serialize(saveFile, buffer);

                var stream = File.OpenWrite("objectdata.nrs");
                stream.Write(buffer, 0, bytesWritten);
                stream.Close();
            }

            {
                //TimelineStorage timelinesStorage = new TimelineStorage();
                //var timeline = game.TimelineEntity.GetComponentOfType<WorldTemplate>();
                //timelinesStorage.FillFrom(timeline);
                //{

                //    FlatBufferSerializer serializer = new FlatBufferSerializer(FlatBufferDeserializationOption.Greedy);
                //    int maxBytesNeeded = serializer.GetMaxSize(timelinesStorage);

                //    int byteNeeded = serializer.GetMaxSize(timelinesStorage.CurrentTimelineLayer.WorldTiles[50 * 10]);

                //    byte[] buffer = new byte[maxBytesNeeded];

                //    int bytesWritten = serializer.Serialize(timelinesStorage, buffer);

                //    var stream = File.OpenWrite("chunksmemory.nrs");                
                //    stream.Write(buffer,0, bytesWritten);
                //    stream.Close();
                //}
            }
        }

        public static void SaveMap(String pathToFolder, WorldMap map, NamelessGame game)
        {
            WorldMapStorage mapStorage = new WorldMapStorage();
            mapStorage.FillFrom(map);
            {
                FlatBufferSerializer serializer = new FlatBufferSerializer(FlatBufferDeserializationOption.Greedy);
                int maxBytesNeeded = GetMaxSizeForTypeAndSave(mapStorage);

                byte[] buffer = new byte[maxBytesNeeded];

                int bytesWritten = serializer.Serialize(mapStorage, buffer);

                if(!Directory.Exists("SavedMaps"))
                {
                    Directory.CreateDirectory("SavedMaps");
                }
                var stream = File.Create("SavedMaps\\chunksmemory.nrs");
                stream.Write(buffer, 0, bytesWritten);
                stream.Close();

                LoadWorldMap("SavedMaps", "chunksmemory.nrs");
            }
        }

        public static void SaveWorldTemplate(String pathToFolder, string filename, WorldTemplate worldTemplate)
        {
            var storage = new WorldTemplateStorage();
            storage.FillFrom(worldTemplate);
            {
                FlatBufferSerializer serializer = new FlatBufferSerializer(FlatBufferDeserializationOption.Greedy);
                int maxBytesNeeded = GetMaxSizeForTypeAndSave(storage);

                byte[] buffer = new byte[maxBytesNeeded];

                int bytesWritten = serializer.Serialize(storage, buffer);

                if (!Directory.Exists(pathToFolder))
                {
                    Directory.CreateDirectory(pathToFolder);
                }
                var stream = File.Create(pathToFolder+"\\"+ filename);
                stream.Write(buffer, 0, bytesWritten);
                stream.Close();
            }
        }



        public static void LoadGame(String pathToFolder, NamelessGame game)
        {
            {
                Type iStorageInterfaceType = typeof(IStorage<>);
                var buffer = File.ReadAllBytes("objectdata.nrs");
                var saveFile = FlatBufferSerializer.Default.Parse<NamelessRogueSaveFile>(buffer);

                saveFile.ComponentTypeToStorge.Clear();
                saveFile.StoragesDictionary.Clear();
                saveFile.FillInfrastructureCollections();

                List<Entity> entities = new List<Entity>();
                foreach (var entityStorage in saveFile.EntityStorageTable)
                {
                    var entity = new Entity(new Guid(entityStorage.Id));
                    entities.Add(entity);
                }

                foreach (var typePair in saveFile.ComponentTypeToStorge)
                {
                    if (typePair.Key == typeof(Entity) || typePair.Key == typeof(IEntity))
                    {
                        continue;
                    }
                    var enumer = saveFile.StoragesDictionary[typePair.Value].GetEnumerator();

                    while (enumer.MoveNext())
                    {
                        var storage = enumer.Current;

                        Component component = (Component)typePair.Key.GetConstructor(Type.EmptyTypes).Invoke(null);

                        storage.FillTo(component.CastToReflected(typePair.Key));

                       // EntityInfrastructureManager.AddComponent(component.ParentEntityId, component);
                    }
   
                }
            }      
            
            {
                var buffer = File.ReadAllBytes("chunksmemory.nrs");
                var saveFile = FlatBufferSerializer.Default.Parse<TimelineStorage>(buffer);
                WorldTemplate timeLine = new WorldTemplate(0);
                saveFile.FillTo(timeLine);

                timeLine.WorldMap.Chunks.WorldMap = timeLine.WorldMap;
                //TO DO: serialize properly
                timeLine.WorldMap.Chunks.WorldSettings = game.WorldSettings;

                foreach (var chunk in timeLine.WorldMap.Chunks.Chunks)
                {
                    chunk.Value.ChunkContainer = timeLine.WorldMap.Chunks;
                }

                var entity = new Entity(timeLine.ParentEntityId);
                entity.AddComponent(timeLine);

                game.CameraEntity = game.GetEntityByComponentClass<ConsoleCamera>();
                game.Commander = game.GetEntityByComponentClass<Commander>().GetComponentOfType<Commander>();
                game.PlayerEntity = game.GetEntityByComponentClass<Player>();
                game.TimelineEntity = entity;
                game.CursorEntity = game.GetEntityByComponentClass<Cursor>();
                game.FollowedByCameraEntity = game.GetEntityByComponentClass<FollowedByCamera>();
            }
        }

        public static WorldMap LoadWorldMap(String pathToFolder, string filename)
        {
            var buffer = File.ReadAllBytes(pathToFolder + "\\" + filename);
            var saveFile = FlatBufferSerializer.Default.Parse<WorldMapStorage>(buffer);
            return saveFile;
        }

        public static WorldTemplate LoadWorldTemplate(String pathToFolder, string filename)
        {
            var buffer = File.ReadAllBytes(pathToFolder + "\\" + filename);
            WorldTemplate saveFile = FlatBufferSerializer.Default.Parse<WorldTemplateStorage>(buffer);
            return saveFile;
        }


        public static void BuildAndSaveAlphaWorld()
        {
            var worldTemplate = LoadWorldTemplate("Worlds", "Alpha World.nrwf");
            var verticalRoadY = 8;
            var horizontalRoadX = 5;
            for (int x = 0; x<worldTemplate.WorldSize.X; x++)
            {
                var worldTile = worldTemplate.WorldMap.WorldTiles[x, verticalRoadY];
                var buildingList = new List<MapBuilding>();
                buildingList.Add(new MapBuilding() { Name = "road_horizontal" });
                worldTile.Buildings = buildingList.ToArray();
            }

            for (int y = 3; y < verticalRoadY+1; y++)
            {
                var worldTile = worldTemplate.WorldMap.WorldTiles[horizontalRoadX, y];
                var buildingList = new List<MapBuilding>(worldTile.Buildings);
                buildingList.Add(new MapBuilding() { Name = "road_vertical" });
                worldTile.Buildings = buildingList.ToArray();
            }
            Point center = default;
            for (int x = 0; x < worldTemplate.WorldSize.X; x++)
            {
                for (int y = 0; y < worldTemplate.WorldSize.X; y++)
                {
                    var worldTile = worldTemplate.WorldMap.WorldTiles[x, y];

                    if(worldTile.Buildings.Length>1)
                    {
                        worldTile.Buildings = new MapBuilding[] { new MapBuilding() { Name = "road_crossroads" } };
                        center = new Point(x-1, y-1);
                    }
                }
            }

            {
                var worldTile = worldTemplate.WorldMap.WorldTiles[center.X, center.Y];
                worldTile.Buildings = new MapBuilding[] { new MapBuilding() { Name = "the_hub_se" } };
            }

            SaveWorldTemplate("Worlds", "Alpha World.nrwf", worldTemplate);
        }


        static int GetMaxSizeForTypeAndSave(object obj)
        {
            var typeString = obj.GetType().Name;
            var hasValue = ByteSizes.MaxSizesEvaluated.Any(x => x.Key == typeString);
            var size = ByteSizes.MaxSizesEvaluated.FirstOrDefault(x => x.Key == typeString);
            if (!hasValue)
            {
                FlatBufferSerializer serializer = new FlatBufferSerializer(FlatBufferDeserializationOption.Greedy);
                int maxBytesNeeded = serializer.GetMaxSize(obj.CastToReflected(obj.GetType()));

                ByteSizes.MaxSizesEvaluated.Add(new KeyValuePair<string, int>(typeString, maxBytesNeeded));

                XmlSerializer xmlSer = new XmlSerializer(typeof(ByteSizesStorage));
                using (var stream = File.OpenWrite("ByteSizesStorage.xml"))
                {
                    xmlSer.Serialize(stream, ByteSizes);
                }
                return maxBytesNeeded;
            }
            else
            {
                return size.Value;
            }
        }
    }
}

