
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class ActionPointsStorage : IStorage<NamelessRogue.Engine.Components.Interaction.ActionPoints>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public Int32 Points { get; set; }

        public void FillFrom(NamelessRogue.Engine.Components.Interaction.ActionPoints component)
        {

            this.Points = component.Points;

            this.Id = component.Id == null ? null : component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId == null ? null : component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.Interaction.ActionPoints component)
        {

            component.Points = this.Points;

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Components.Interaction.ActionPoints (ActionPointsStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Components.Interaction.ActionPoints result = new NamelessRogue.Engine.Components.Interaction.ActionPoints();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator ActionPointsStorage (NamelessRogue.Engine.Components.Interaction.ActionPoints  component)
        {
            if(component == null) { return null; }
            ActionPointsStorage result = new ActionPointsStorage();
            result.FillFrom(component);
            return result;
        }

    }

}