
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class CharacterStorage : IStorage<NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character component)
        {

            this.Id = component.Id == null ? null : component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId == null ? null : component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character component)
        {
            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);
        }

        public static implicit operator NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character (CharacterStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character result = new NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character("");
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator CharacterStorage (NamelessRogue.Engine.Components.AI.NonPlayerCharacter.Character  component)
        {
            if(component == null) { return null; }
            CharacterStorage result = new CharacterStorage();
            result.FillFrom(component);
            return result;
        }

    }

}