
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferEnum(typeof(Int32))]
    public enum ItemQualityStorage : Int32 
    {
         Terrible,
         Poor,
         Shoddy,
         Normal,
         Good,
         Excellent,
         Superb,
    
    }
}
