
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferEnum(typeof(Int32))]
    public enum SlotStorage : Int32 
    {
         Head,
         Torso,
         LefHand,
         RightHand,
         Legs,
         Feet,
         Ring1,
         Ring2,
         Neck,
         Hands,
    
    }
}
