
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
using Microsoft.Xna.Framework;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class WaterBorderLineStorage : IStorage<NamelessRogue.Engine.Generation.World.Waypoints>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public IList<Vector2Storage> Points { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.Waypoints component)
        {
            
            this.Points = new List<Vector2Storage>(component.Points.Select(x=>(Vector2Storage)x));

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.Waypoints component)
        {
            component.Points = new List<Vector2>(this.Points.Select(x=>(Vector2)x));
        }

        public static implicit operator NamelessRogue.Engine.Generation.World.Waypoints(WaterBorderLineStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Generation.World.Waypoints result = new NamelessRogue.Engine.Generation.World.Waypoints();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator WaterBorderLineStorage (NamelessRogue.Engine.Generation.World.Waypoints component)
        {
            if(component == null) { return null; }
            WaterBorderLineStorage result = new WaterBorderLineStorage();
            result.FillFrom(component);
            return result;
        }

    }

}