<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
	<MonoGameExtendedPipelineReferencePath>$(MSBuildThisFileDirectory)pipeline-references</MonoGameExtendedPipelineReferencePath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Content\ChunkShader3D.fx" />
    <None Remove="Content\Common.fx" />
    <None Remove="Content\DFfont.png" />
    <None Remove="Content\Shader.fx" />
    <None Remove="Content\TreeShader.fx" />
    <None Remove="log4net.config" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content\Common.fx" />
    <Content Include="Content\Sprites\cursorBig.png" />
    <Content Include="Content\Sprites\cursorSmall.png" />
    <Content Include="Content\TreeShader.fx" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content\ChunkShader3D.fx" />
    <Content Include="Content\DFfont.png" />
    <Content Include="Content\Shader.fx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="log4net.config" />
  </ItemGroup>
		
	
  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="4.1.0" />
    <PackageReference Include="FbxSharp" Version="0.9.0" />
    <PackageReference Include="FlatSharp" Version="6.3.5" />
    <PackageReference Include="ImGui.NET" Version="1.89.4" />
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="Markov" Version="2.0.0" />
    <PackageReference Include="MonoGame.Aseprite" Version="6.2.0" />
    <PackageReference Include="MonoGame.Extended" Version="4.1.0" />
    <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="4.1.0" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RogueSharp" Version="4.2.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="TiledCSPlus" Version="4.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AstarNavigatorNetCore\AstarNavigatorNetCore.csproj" />
    <ProjectReference Include="..\VoronoiLib\VoronoiLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Content\Buildings\ApartmentBlockFloor.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\ApartmentBlockFloorGroundLevel.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\ApartmentBlockFloor_backup.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\ApartmentBlockTopFloor.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\Buildings.tiled-project">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\Buildings.tiled-session">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\DFfont.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\road_crossroads.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\road_horizontal.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\road_vertical.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\symbols.tsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\test.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\the_hub_se.tmx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Buildings\tileset2.tsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Credits.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Fonts\AnonymousPro-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\MusicPack\PackConfigSample.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\MusicPack\PackConfig.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\MusicPack\Realm of Fantasy.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\MusicPack\World Map.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\AnimatedFurniture\computer1.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\AnimatedFurniture\computer2.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\drone_recon.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\energybar.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\Fire\fire1.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\Fire\fire2.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\Fire\fire3.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\healthbar.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\lightning.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\Xelanoi.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\ZeroAndOne.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\Sprites\ZeroAndOne2.ase">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Worlds\Alpha World.nrwf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<ItemGroup>
		<Content Include="Content\GameObjects\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Content\Models\**" />
	  <Compile Remove="Content\Sprites\Furniture\**" />
	  <Compile Remove="Content\Sprites\MainMenuScreen\**" />
	  <Compile Remove="Content\T4CodeGenerators\**" />
	  <Compile Remove="Engine\Components\Environment\Buildings\**" />
	  <Compile Remove="Engine\Generation\Items\**" />
	  <Compile Remove="Engine\_3DUtility\**" />
	  <Compile Remove="NewFolder\**" />
	  <EmbeddedResource Remove="Content\Models\**" />
	  <EmbeddedResource Remove="Content\Sprites\Furniture\**" />
	  <EmbeddedResource Remove="Content\Sprites\MainMenuScreen\**" />
	  <EmbeddedResource Remove="Content\T4CodeGenerators\**" />
	  <EmbeddedResource Remove="Engine\Components\Environment\Buildings\**" />
	  <EmbeddedResource Remove="Engine\Generation\Items\**" />
	  <EmbeddedResource Remove="Engine\_3DUtility\**" />
	  <EmbeddedResource Remove="NewFolder\**" />
	  <None Remove="Content\Models\**" />
	  <None Remove="Content\Sprites\Furniture\**" />
	  <None Remove="Content\Sprites\MainMenuScreen\**" />
	  <None Remove="Content\T4CodeGenerators\**" />
	  <None Remove="Engine\Components\Environment\Buildings\**" />
	  <None Remove="Engine\Generation\Items\**" />
	  <None Remove="Engine\_3DUtility\**" />
	  <None Remove="NewFolder\**" />
	</ItemGroup>
	
  <ItemGroup>
    <Folder Include="Content\GameObjects\Misc\" />
    <Folder Include="Content\obj\Windows\AnimatedCharacters\" />
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>