using FlatSharp;
using Microsoft.Xna.Framework;
using NamelessRogue.Engine.Components.ChunksAndTiles;
using NamelessRogue.Engine.Components.Physical;
using NamelessRogue.Engine.Components.Rendering;
using NamelessRogue.Engine.Factories;
using NamelessRogue.Engine.Generation;
using NamelessRogue.Engine.Generation.World;
using NamelessRogue.Engine.Serialization;
using NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses;
using NamelessRogue.Engine.Utility;
using NamelessRogue.shell;
using Newtonsoft.Json;
using RogueSharp.Random;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

namespace NamelessRogue
{
    /// <summary>
    /// The main class.
    /// </summary>
    public static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            //SerializationCodeGenerator.GenerateStorages(typeof(NamelessRogue.Engine.Generation.World.WorldTemplate));
            //return;

            SaveManager.Init();
            SaveManager.BuildAndSaveAlphaWorld();
            //// return;
            using (var game = new NamelessGame())
            {
                game.Run();
            }
        }    
    }
}
