using FlatSharp.Attributes;
using Microsoft.Xna.Framework;
using NamelessRogue.Engine.Components.ChunksAndTiles;
using NamelessRogue.Engine.Infrastructure;
using NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Utility;
using System;
using System.Collections.Generic;
using System.Text;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace NamelessRogue.Engine.Serialization.CustomSerializationClasses
{
	[FlatBufferTable]
	public class ChunkStorage : IStorage<Chunk>
	{
		[FlatBufferItem(1)] public PointStorage ChunkWorldMapLocationPoint { get; set; }
		[FlatBufferItem(2)] public BoundingBoxStorage Bounds { get; set; }
		[FlatBufferItem(3)] public TileStorage[] Tiles { get; set; }
		[FlatBufferItem(4)] public int ChunkResolution { get; set; }
		[FlatBufferItem(5)] public PointStorage WorldPositionBottomLeftCorner { get; set; }

		public void FillFrom(Chunk component)
		{
			ChunkWorldMapLocationPoint = component.ChunkWorldMapLocationPoint;
			Bounds = new Microsoft.Xna.Framework.BoundingBox(component.Bounds.Min, component.Bounds.Max);
			WorldPositionBottomLeftCorner = component.WorldPositionBottomLeftCorner;
			var tiles = component.GetChunkTiles();
			if (tiles != null)
			{
				ChunkResolution = Constants.ChunkSize;
                var queue = new Queue<TileStorage>();
                for (int i = 0; i < tiles.GetLength(0); i++)
                {
                    for (int j = 0; j < tiles.GetLength(1); j++)
                    {
                        for (int k = 0; k < tiles.GetLength(2); k++)
                        {
                            queue.Enqueue(tiles[i][j][k]);
                        }
                    }
                }
				Tiles = queue.ToArray();

            }			
		}

		public void FillTo(Chunk component)
		{
			component.ChunkWorldMapLocationPoint = ChunkWorldMapLocationPoint;
			component.WorldPositionBottomLeftCorner = WorldPositionBottomLeftCorner;
			component.Bounds = Bounds;
			if (Tiles != null)
			{
				Tile[][][] tiles;
				tiles = new Tile[Constants.ChunkSize][][];
				for (var x = 0; x < Constants.ChunkSize; x++)
				{
					tiles[x] = new Tile[Constants.ChunkSize][];
					for(int y = 0; y < Constants.ChunkSize; y++ )
					{
						tiles[x][y] = new Tile[Constants.ChunkHeight];
                    }
				}


				var index = 0;
                for (int x = 0; x < Constants.ChunkSize; x++)
                {
                    for (int y = 0; y < Constants.ChunkSize; y++)
                    {
                        for (int z = 0; z < Constants.ChunkHeight; z++)
                        {
                            tiles[x][y][z] = Tiles[index++];
                        }
                    }
                }

                component.SetChunkTiles(tiles);
            }

			//obviously, it was not generated right now
			component.JustCreated = false;
		}
	}
}
