
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class NamesGeneratorStorage : IStorage<NamelessRogue.Engine.Generation.NamesGenerator>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        public void FillFrom(NamelessRogue.Engine.Generation.NamesGenerator component)
        {

        }

        public void FillTo(NamelessRogue.Engine.Generation.NamesGenerator component)
        {


        }

        public static implicit operator NamelessRogue.Engine.Generation.NamesGenerator (NamesGeneratorStorage thisType)
        {
            if (thisType == null) { return null; }
            NamelessRogue.Engine.Generation.NamesGenerator result = new NamelessRogue.Engine.Generation.NamesGenerator();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator NamesGeneratorStorage (NamelessRogue.Engine.Generation.NamesGenerator  component)
        {
            if (component == null) { return null; }
            NamesGeneratorStorage result = new NamesGeneratorStorage();
            result.FillFrom(component);
            return result;
        }

    }

}