
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class TileForPaintingStorage : IStorage<NamelessRogue.Engine.Generation.World.TileForPainting>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public IList<WaypointsStorage> WaterBorderLines { get; set; }

        [FlatBufferItem(3)]  public IList<WaypointsStorage> Roads { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.TileForPainting component)
        {
            
            this.WaterBorderLines = new List<WaypointsStorage>(component.WaterBorderLines.Select(x=>(WaypointsStorage)x));
            
            this.Roads = new List<WaypointsStorage>(component.Roads.Select(x=>(WaypointsStorage)x));

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.TileForPainting component)
        {

            component.WaterBorderLines = new List<NamelessRogue.Engine.Generation.World.Waypoints>(this.WaterBorderLines.Select(x=>(NamelessRogue.Engine.Generation.World.Waypoints)x));

            component.Roads = new List<NamelessRogue.Engine.Generation.World.Waypoints>(this.Roads.Select(x=>(NamelessRogue.Engine.Generation.World.Waypoints)x));


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.TileForPainting (TileForPaintingStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Generation.World.TileForPainting result = new NamelessRogue.Engine.Generation.World.TileForPainting();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator TileForPaintingStorage (NamelessRogue.Engine.Generation.World.TileForPainting  component)
        {
            if(component == null) { return null; }
            TileForPaintingStorage result = new TileForPaintingStorage();
            result.FillFrom(component);
            return result;
        }

    }

}