
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class WorldTileStorage : IStorage<NamelessRogue.Engine.Generation.World.WorldTile>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public TerrainTypesStorage Terrain { get; set; }

        [FlatBufferItem(3)]  public BiomesStorage Biome { get; set; }

        [FlatBufferItem(4)]  public MapBuildingStorage Building { get; set; }

        [FlatBufferItem(5)]  public MapArtifactStorage Artifact { get; set; }

 

        [FlatBufferItem(8)]  public RegionStorage Continent { get; set; }

        [FlatBufferItem(9)]  public RegionStorage LandmarkRegion { get; set; }

        [FlatBufferItem(11)]  public PointStorage WorldBoardPosiiton { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.WorldTile component)
        {

            this.Terrain = (TerrainTypesStorage)component.Terrain;

            this.Biome = (BiomesStorage)component.Biome;

            this.Building = component.Building;


            this.WorldBoardPosiiton = component.WorldBoardPosiiton;

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.WorldTile component)
        {

            component.Terrain = (Infrastructure.TerrainTypes)this.Terrain;

            component.Biome = (Generation.World.Biomes)this.Biome;

            component.Building = this.Building;

            component.WorldBoardPosiiton = this.WorldBoardPosiiton;


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.WorldTile (WorldTileStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Generation.World.WorldTile result = new NamelessRogue.Engine.Generation.World.WorldTile();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator WorldTileStorage (NamelessRogue.Engine.Generation.World.WorldTile  component)
        {
            if(component == null) { return null; }
            WorldTileStorage result = new WorldTileStorage();
            result.FillFrom(component);
            return result;
        }

    }

}