
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
using NamelessRogue.Engine.Generation.World;
using NamelessRogue.Engine.Generation.World.TerrainFeatures;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class WorldMapStorage : IStorage<NamelessRogue.Engine.Generation.World.WorldMap>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public Int32 Resolution { get; set; }

        [FlatBufferItem(3)]  public WorldTileStorage[] WorldTiles { get; set; }
        [FlatBufferItem(4)]  public IList<WaypointsStorage> RiverBorderLines { get; set; }

        [FlatBufferItem(5)]  public IList<WaypointsStorage> Roads { get; set; }

        [FlatBufferItem(6)]  public TileForPaintingStorage[] TerrainFeatures { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.WorldMap component)
        {

            this.Resolution = component.Resolution;

            var queue = new Queue<WorldTile>();
            for (int y = 0; y < Resolution; y++)
            {
                for (int x = 0; x < Resolution; x++)
                {
                    queue.Enqueue(component.WorldTiles[y, x]);
                }
            }
            WorldTiles = queue.Select(x=>(WorldTileStorage)x).ToArray();
            
            this.RiverBorderLines = new List<WaypointsStorage>(component.RiverBorderLines.Select(x=>(WaypointsStorage)x));
            
            this.Roads = new List<WaypointsStorage>(component.Roads.Select(x=>(WaypointsStorage)x));


            var queueTF = new Queue<TileForPainting>();
            for (int i = 0; i < Resolution  ; i++)
            {
                for (int j = 0; j < Resolution; j++)
                {
                    queueTF.Enqueue(component.TerrainFeatures[i][j]);
                }
            }
            TerrainFeatures = queueTF.Select(x => (TileForPaintingStorage)x).ToArray();
        }

        public void FillTo(NamelessRogue.Engine.Generation.World.WorldMap component)
        {

            component.Resolution = this.Resolution;

            component.WorldTiles = new WorldTile[Resolution, Resolution];

            {
                var index = 0;

                for (int y = 0; y < Resolution; y++)
                {
                    for (int x = 0; x < Resolution; x++)
                    {
                        component.WorldTiles[y, x] = WorldTiles[index++];
                    }
                }
            }

            component.RiverBorderLines = new List<NamelessRogue.Engine.Generation.World.Waypoints>(this.RiverBorderLines.Select(x=>(NamelessRogue.Engine.Generation.World.Waypoints)x));

            component.Roads = new List<NamelessRogue.Engine.Generation.World.Waypoints>(this.Roads.Select(x=>(NamelessRogue.Engine.Generation.World.Waypoints)x));

            component.TerrainFeatures = new TileForPainting[Resolution][];

            for(int i = 0; i < Resolution;i++)
            {
                component.TerrainFeatures[i] = new TileForPainting[Resolution];
            }

            {
                var index = 0;
                for (int x = 0; x < Resolution; x++)
                {
                    for (int y = 0; y < Resolution; y++)
                    {
                        component.TerrainFeatures[x][y] = TerrainFeatures[index++];
                    }
                }
            }


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.WorldMap (WorldMapStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Generation.World.WorldMap result = new NamelessRogue.Engine.Generation.World.WorldMap();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator WorldMapStorage (NamelessRogue.Engine.Generation.World.WorldMap  component)
        {
            if(component == null) { return null; }
            WorldMapStorage result = new WorldMapStorage();
            result.FillFrom(component);
            return result;
        }

    }

}