
// AUTOGENERATED
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FlatSharp.Attributes;
using NamelessRogue.Engine.Serialization.SerializationIfrastructure;
using NamelessRogue.Engine.Serialization.CustomSerializationClasses;
using Microsoft.Xna.Framework;
namespace NamelessRogue.Engine.Serialization.AutogeneratedSerializationClasses
{
    [FlatBufferTable]
    public class WorldTemplateStorage : IStorage<NamelessRogue.Engine.Generation.World.WorldTemplate>
    {
        [FlatBufferItem(0)]  public string Id { get; set; }
        [FlatBufferItem(1)]  public string ParentEntityId { get; set; }
        [FlatBufferItem(2)]  public Int32 Seed { get; set; }

        [FlatBufferItem(3)]  public String Name { get; set; }

        [FlatBufferItem(4)]  public WorldSizeNameStorage WorldSizeName { get; set; }

        [FlatBufferItem(5)]  public Vector2Storage WorldSize { get; set; }

        [FlatBufferItem(6)]  public WaterLevelStorage WaterType { get; set; }

        [FlatBufferItem(7)]  public Int32 NeighbouringCityCount { get; set; }

        [FlatBufferItem(8)]  public DateTimeStorage CurrentTime { get; set; }

        [FlatBufferItem(9)]  public Vector2Storage CitySize { get; set; }

        [FlatBufferItem(10)]  public WorldMapStorage WorldMap { get; set; }

        public void FillFrom(NamelessRogue.Engine.Generation.World.WorldTemplate component)
        {

            this.Seed = component.Seed;

            this.Name = component.Name;

            this.WorldSizeName = (WorldSizeNameStorage)component.WorldSizeName;

            this.WorldSize = new Vector2(component.WorldSize.X, component.WorldSize.Y);

            this.WaterType = (WaterLevelStorage)component.WaterType;

            this.NeighbouringCityCount = component.NeighbouringCityCount;

            this.CurrentTime = component.CurrentTime;

            this.CitySize = new Vector2(component.CitySize.X, component.CitySize.Y);

            this.WorldMap = component.WorldMap;

            this.Id = component.Id == null ? null : component.Id.ToString();

            this.ParentEntityId = component.ParentEntityId == null ? null : component.ParentEntityId.ToString();

        }

        public void FillTo(NamelessRogue.Engine.Generation.World.WorldTemplate component)
        {

            component.Seed = this.Seed;

            component.Name = this.Name;

            component.WorldSizeName = (NamelessRogue.Engine.Generation.World.WorldSizeName)this.WorldSizeName;

            component.WorldSize = new System.Numerics.Vector2(WorldSize.X, WorldSize.Y);

            component.WaterType = (NamelessRogue.Engine.Generation.World.WaterLevel)this.WaterType;

            component.NeighbouringCityCount = this.NeighbouringCityCount;

            component.CurrentTime = this.CurrentTime;

            component.CitySize = new System.Numerics.Vector2(CitySize.X, CitySize.Y);

            component.WorldMap = this.WorldMap;

            component.Id = new Guid(this.Id);

            component.ParentEntityId = new Guid(this.ParentEntityId);


        }

        public static implicit operator NamelessRogue.Engine.Generation.World.WorldTemplate (WorldTemplateStorage thisType)
        {
            if(thisType == null) { return null; }
            NamelessRogue.Engine.Generation.World.WorldTemplate result = new NamelessRogue.Engine.Generation.World.WorldTemplate();
            thisType.FillTo(result);
            return result;
        }

        public static implicit operator WorldTemplateStorage (NamelessRogue.Engine.Generation.World.WorldTemplate  component)
        {
            if(component == null) { return null; }
            WorldTemplateStorage result = new WorldTemplateStorage();
            result.FillFrom(component);
            return result;
        }

    }

}